"""
Report generation service — JSON and styled professional PDF via ReportLab.

PDF Design:
  - Clean A4 light theme (white background)
  - Royal-blue (#1e40af) header and section bars
  - Verdict coloured banner (red / amber / green)
  - Consistent table styling with alternating rows
  - Per-page header/footer via canvas callbacks
"""
from __future__ import annotations
import io
import json
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from models.schemas import AnalysisResult

# ── Palette (RGB 0-1) ──────────────────────────────────────────────────────────
_NAVY       = (0.118, 0.251, 0.686)   # #1e40af — royal blue
_NAVY_DARK  = (0.071, 0.157, 0.525)   # #122585
_NAVY_LIGHT = (0.933, 0.945, 0.988)   # #eef1fc — very light blue tint
_RED        = (0.863, 0.149, 0.149)   # #dc2626
_RED_LIGHT  = (1.000, 0.945, 0.945)   # #fff1f1
_AMBER      = (0.855, 0.463, 0.027)   # #da7607
_AMBER_LIGHT= (1.000, 0.973, 0.937)   # #fff8ef
_GREEN      = (0.086, 0.639, 0.294)   # #16a34a
_GREEN_LIGHT= (0.941, 0.992, 0.953)   # #f0fdf4
_GREY_ROW   = (0.973, 0.973, 0.973)   # alternating row tint
_TEXT_DARK  = (0.067, 0.094, 0.153)   # #111827
_TEXT_MED   = (0.286, 0.353, 0.447)   # #495a72
_TEXT_LIGHT = (0.600, 0.647, 0.710)   # light secondary text


def generate_json_report(result: "AnalysisResult") -> bytes:
    """Serialise the full AnalysisResult to an indented JSON byte string."""
    return result.model_dump_json(indent=2).encode("utf-8")


def generate_pdf_report(result: "AnalysisResult") -> bytes:
    """Create a professionally styled A4 PDF report."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm, mm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, KeepTogether, PageBreak,
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.pdfgen import canvas as rl_canvas

    # ── Colour objects ─────────────────────────────────────────────────────────
    def rgb(*t): return colors.Color(*t)

    C_NAVY       = rgb(*_NAVY)
    C_NAVY_DARK  = rgb(*_NAVY_DARK)
    C_NAVY_LIGHT = rgb(*_NAVY_LIGHT)
    C_RED        = rgb(*_RED)
    C_RED_LIGHT  = rgb(*_RED_LIGHT)
    C_AMBER      = rgb(*_AMBER)
    C_AMBER_LIGHT= rgb(*_AMBER_LIGHT)
    C_GREEN      = rgb(*_GREEN)
    C_GREEN_LIGHT= rgb(*_GREEN_LIGHT)
    C_GREY_ROW   = rgb(*_GREY_ROW)
    C_TEXT_DARK  = rgb(*_TEXT_DARK)
    C_TEXT_MED   = rgb(*_TEXT_MED)
    C_TEXT_LIGHT = rgb(*_TEXT_LIGHT)
    C_WHITE      = colors.white
    C_BLACK      = colors.black
    C_LG         = colors.Color(0.878, 0.878, 0.878)  # light grey border

    verdict_c = {"FAKE": C_RED, "SUSPICIOUS": C_AMBER, "LEGITIMATE": C_GREEN}
    verdict_cl= {"FAKE": C_RED_LIGHT, "SUSPICIOUS": C_AMBER_LIGHT, "LEGITIMATE": C_GREEN_LIGHT}
    vc  = verdict_c.get(result.verdict, C_AMBER)
    vcl = verdict_cl.get(result.verdict, C_AMBER_LIGHT)
    sev_c = {"critical": C_RED, "high": C_AMBER, "medium": C_NAVY, "low": C_TEXT_LIGHT}

    # ── Page canvas callbacks (per-page header stripe + footer) ───────────────
    PAGE_W, PAGE_H = A4

    def on_first_page(canv, doc):
        _draw_page_footer(canv, doc)

    def on_later_pages(canv, doc):
        _draw_page_header_stripe(canv, doc)
        _draw_page_footer(canv, doc)

    def _draw_page_header_stripe(canv, doc):
        canv.saveState()
        canv.setFillColor(C_NAVY)
        canv.rect(0, PAGE_H - 1.1 * cm, PAGE_W, 1.1 * cm, fill=1, stroke=0)
        canv.setFont("Helvetica-Bold", 8)
        canv.setFillColor(C_WHITE)
        canv.drawString(1.8 * cm, PAGE_H - 0.75 * cm, "APK Guardian  ·  Security Analysis Report")
        canv.drawRightString(PAGE_W - 1.8 * cm, PAGE_H - 0.75 * cm, result.filename or "")
        canv.restoreState()

    def _draw_page_footer(canv, doc):
        canv.saveState()
        canv.setStrokeColor(C_LG)
        canv.setLineWidth(0.5)
        canv.line(1.8 * cm, 1.6 * cm, PAGE_W - 1.8 * cm, 1.6 * cm)
        canv.setFont("Helvetica", 7)
        canv.setFillColor(C_TEXT_LIGHT)
        canv.drawString(1.8 * cm, 1.1 * cm,
                        f"Generated by APK Guardian v1.0.0  ·  {result.timestamp}  ·  For security research purposes only.")
        canv.drawRightString(PAGE_W - 1.8 * cm, 1.1 * cm,
                             f"Page {canv.getPageNumber()}")
        canv.restoreState()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.8 * cm,
        rightMargin=1.8 * cm,
        topMargin=2.0 * cm,
        bottomMargin=2.2 * cm,
        title=f"APK Guardian — {result.filename}",
        author="APK Guardian",
        subject="Android APK Security Analysis Report",
    )

    # ── Paragraph styles ───────────────────────────────────────────────────────
    def S(name, **kw):
        kw.setdefault("fontName", "Helvetica")
        kw.setdefault("fontSize", 9)
        kw.setdefault("textColor", C_TEXT_DARK)
        kw.setdefault("leading", 12)
        return ParagraphStyle(name, **kw)

    s_title   = S("T", fontName="Helvetica-Bold", fontSize=22, textColor=C_WHITE,
                  alignment=TA_CENTER, spaceAfter=3, leading=26)
    s_sub     = S("Sub", fontSize=9, textColor=rgb(0.8, 0.85, 0.97),
                  alignment=TA_CENTER, spaceAfter=0)
    s_section = S("Sec", fontName="Helvetica-Bold", fontSize=11, textColor=C_WHITE,
                  leading=14)
    s_normal  = S("N")
    s_mono    = S("M", fontName="Courier", fontSize=8, textColor=C_TEXT_DARK)
    s_bold    = S("B", fontName="Helvetica-Bold")
    s_small   = S("Sm", fontSize=7.5, textColor=C_TEXT_MED)
    s_red     = S("R", fontName="Helvetica-Bold", fontSize=8, textColor=C_RED)
    s_green   = S("G", fontName="Helvetica-Bold", fontSize=8, textColor=C_GREEN)
    s_center  = S("Cen", alignment=TA_CENTER)

    story = []
    W = doc.width

    # ─────────────────────────────────────────────────────────────────────────
    # SECTION HEADER HELPER
    # ─────────────────────────────────────────────────────────────────────────
    def section_header(text):
        """Navy bar with white text — used for every section heading."""
        t = Table([[Paragraph(text, s_section)]], colWidths=[W])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), C_NAVY),
            ("TOPPADDING",    (0,0), (-1,-1), 7),
            ("BOTTOMPADDING", (0,0), (-1,-1), 7),
            ("LEFTPADDING",   (0,0), (-1,-1), 10),
            ("RIGHTPADDING",  (0,0), (-1,-1), 10),
            ("BOX",           (0,0), (-1,-1), 0, C_NAVY),
        ]))
        story.append(t)
        story.append(Spacer(1, 6))

    def table_style(header_bg=None):
        """Standard table style with navy header row and alternating body rows."""
        hbg = header_bg or C_NAVY
        return TableStyle([
            ("BACKGROUND",    (0,0), (-1,0),  hbg),
            ("TEXTCOLOR",     (0,0), (-1,0),  C_WHITE),
            ("FONTNAME",      (0,0), (-1,0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0,0), (-1,0),  8.5),
            ("FONTSIZE",      (0,1), (-1,-1), 8.5),
            ("ROWBACKGROUNDS",(0,1), (-1,-1), [C_WHITE, C_GREY_ROW]),
            ("GRID",          (0,0), (-1,-1), 0.3, C_LG),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LEFTPADDING",   (0,0), (-1,-1), 7),
            ("RIGHTPADDING",  (0,0), (-1,-1), 7),
            ("VALIGN",        (0,0), (-1,-1), "TOP"),
        ])

    # ═════════════════════════════════════════════════════════════════════════
    # 1. COVER BANNER
    # ═════════════════════════════════════════════════════════════════════════
    cover = Table([
        [Paragraph("🛡  APK Guardian", s_title)],
        [Paragraph("Security Analysis Report", s_sub)],
    ], colWidths=[W])
    cover.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_NAVY_DARK),
        ("TOPPADDING",    (0,0), (-1,-1), 16),
        ("BOTTOMPADDING", (0,0), (-1,-1), 16),
        ("BOX",           (0,0), (-1,-1), 1.5, C_NAVY),
    ]))
    story.append(cover)
    story.append(Spacer(1, 10))

    # ═════════════════════════════════════════════════════════════════════════
    # 2. VERDICT BANNER
    # ═════════════════════════════════════════════════════════════════════════
    verdict_icon = {"FAKE": "✗", "SUSPICIOUS": "⚠", "LEGITIMATE": "✓"}.get(result.verdict, "?")
    risk_label   = "HIGH" if result.risk_score >= 70 else ("MEDIUM" if result.risk_score >= 40 else "LOW")

    s_verdict_big = S("VB", fontName="Helvetica-Bold", fontSize=20, textColor=vc,
                      alignment=TA_CENTER, leading=24)
    s_verdict_lbl = S("VL", fontSize=8.5, textColor=C_TEXT_MED, alignment=TA_CENTER)
    s_verdict_val = S("VV", fontName="Helvetica-Bold", fontSize=15, textColor=vc,
                      alignment=TA_CENTER, leading=18)

    verdict_data = [[
        Paragraph(f"{verdict_icon}  {result.verdict}", s_verdict_big),
        Paragraph(f"{result.risk_score:.0f}", s_verdict_val),
        Paragraph(f"{result.confidence:.0f}%", s_verdict_val),
        Paragraph(result.filename or "—", S("FN", fontSize=8, textColor=C_TEXT_MED,
                                             alignment=TA_CENTER, leading=10)),
    ], [
        Paragraph("Verdict", s_verdict_lbl),
        Paragraph(f"Risk Score  ·  {risk_label} RISK", s_verdict_lbl),
        Paragraph("ML Confidence", s_verdict_lbl),
        Paragraph("File", s_verdict_lbl),
    ]]
    vt = Table(verdict_data, colWidths=[W*0.30, W*0.22, W*0.22, W*0.26])
    vt.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), vcl),
        ("BOX",           (0,0), (-1,-1), 1.5, vc),
        ("LINEAFTER",     (0,0), (2,1),   0.4, C_LG),
        ("TOPPADDING",    (0,0), (-1,-1), 10),
        ("BOTTOMPADDING", (0,0), (-1,-1), 10),
        ("ALIGN",         (0,0), (-1,-1), "CENTER"),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
    ]))
    story.append(vt)
    story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 3. APPLICATION METADATA
    # ═════════════════════════════════════════════════════════════════════════
    section_header("📱  Application Metadata")
    meta = result.metadata
    meta_rows = [
        ["Field", "Value"],
        ["Package Name",        Paragraph(meta.package_name or "—", s_mono)],
        ["App Name",            meta.app_name or "—"],
        ["Version",             f"{meta.version_name}  (build {meta.version_code})"],
        ["Min SDK / Target SDK",f"API {meta.min_sdk}  /  API {meta.target_sdk}"],
        ["File Size",           f"{meta.file_size_kb / 1024:.2f} MB  ({meta.file_size_kb:.0f} KB)"],
        ["SHA-256",             Paragraph(meta.sha256 or "—", s_mono)],
        ["Analysis Timestamp",  result.timestamp],
        ["Analysis ID",         Paragraph(result.analysis_id, s_mono)],
        ["Model Version",       result.model_version],
    ]
    mt = Table(meta_rows, colWidths=[4.5*cm, W - 4.5*cm])
    mt.setStyle(table_style())
    story.append(mt)
    story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 4. KNOWN BANKING APP WHITELIST
    # ═════════════════════════════════════════════════════════════════════════
    is_known   = getattr(result, "is_known_banking_app", False)
    known_name = getattr(result, "known_app_name", None)
    wl_colour  = C_GREEN if is_known else C_AMBER
    wl_bg      = C_GREEN_LIGHT if is_known else C_AMBER_LIGHT
    wl_icon    = "✓  VERIFIED OFFICIAL BANKING APP" if is_known else "⚠  NOT IN KNOWN BANKING APP WHITELIST"
    wl_sub     = f"Recognised as: {known_name}" if is_known else \
                 "Package name does not match any known legitimate banking application."
    s_wl_title = S("WLT", fontName="Helvetica-Bold", fontSize=10, textColor=wl_colour, leading=14)
    s_wl_sub   = S("WLS", fontSize=8, textColor=C_TEXT_MED, leading=11)
    wl_t = Table([
        [Paragraph(wl_icon, s_wl_title)],
        [Paragraph(wl_sub,  s_wl_sub)],
    ], colWidths=[W])
    wl_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), wl_bg),
        ("BOX",           (0,0), (-1,-1), 1.2, wl_colour),
        ("LINEBELOW",     (0,0), (-1,0),  0.4, C_LG),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING",   (0,0), (-1,-1), 12),
    ]))
    story.append(wl_t)
    story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 5. BANKING POLICY COMPLIANCE
    # ═════════════════════════════════════════════════════════════════════════
    compliance       = getattr(result, "compliance_summary", None)
    policy_violations= getattr(result, "policy_violations", [])

    if compliance:
        section_header("⚖  Banking Policy Compliance")

        comp  = compliance if isinstance(compliance, dict) else compliance.model_dump()
        score = comp.get("compliance_score", 0)
        passed= comp.get("passed", 0)
        total = comp.get("total_policies_checked", 0)
        viols = comp.get("violations", len(policy_violations))
        sevs  = comp.get("severity_counts", {})
        sc_c  = C_GREEN if score >= 75 else (C_AMBER if score >= 50 else C_RED)
        sc_bg = C_GREEN_LIGHT if score >= 75 else (C_AMBER_LIGHT if score >= 50 else C_RED_LIGHT)
        status_txt = "COMPLIANT" if score >= 75 else ("PARTIAL" if score >= 50 else "NON-COMPLIANT")

        s_score_big = S("SB", fontName="Helvetica-Bold", fontSize=22, textColor=sc_c,
                        alignment=TA_CENTER, leading=26)
        s_score_lbl = S("SL", fontSize=8, textColor=C_TEXT_MED, alignment=TA_CENTER)
        s_sev_val   = S("SV", fontName="Helvetica-Bold", fontSize=14, alignment=TA_CENTER, leading=18)
        s_sev_lbl   = S("SVL", fontSize=7.5, textColor=C_TEXT_MED, alignment=TA_CENTER)

        # Row 1: big numbers; Row 2: labels
        sc_data = [[
            Paragraph(f"{score:.0f}%", s_score_big),
            Paragraph(f"{passed} / {total}", S("PP", fontName="Helvetica-Bold", fontSize=18,
                                                textColor=C_GREEN, alignment=TA_CENTER, leading=22)),
            Paragraph(str(viols), S("VV2", fontName="Helvetica-Bold", fontSize=18,
                                    textColor=C_RED if viols else C_GREEN,
                                    alignment=TA_CENTER, leading=22)),
            Paragraph(status_txt, S("ST", fontName="Helvetica-Bold", fontSize=12,
                                    textColor=sc_c, alignment=TA_CENTER, leading=16)),
        ], [
            Paragraph("Compliance Score", s_score_lbl),
            Paragraph("Policies Passed", s_score_lbl),
            Paragraph("Violations", s_score_lbl),
            Paragraph("Status", s_score_lbl),
        ]]
        sc_t = Table(sc_data, colWidths=[W*0.28, W*0.24, W*0.24, W*0.24])
        sc_t.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), sc_bg),
            ("BOX",           (0,0), (-1,-1), 1.2, sc_c),
            ("LINEAFTER",     (0,0), (2,1),   0.4, C_LG),
            ("TOPPADDING",    (0,0), (-1,-1), 10),
            ("BOTTOMPADDING", (0,0), (-1,-1), 10),
            ("ALIGN",         (0,0), (-1,-1), "CENTER"),
            ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(sc_t)
        story.append(Spacer(1, 8))

        # Severity breakdown bar
        SEV_LABELS = ["Critical", "High", "Medium", "Low"]
        SEV_COLORS = [C_RED, C_AMBER, C_NAVY, C_TEXT_LIGHT]
        sev_data = [
            [Paragraph(lbl, S("SHL", fontName="Helvetica-Bold", fontSize=8, textColor=SEV_COLORS[i], alignment=TA_CENTER))
             for i, lbl in enumerate(SEV_LABELS)],
            [Paragraph(str(sevs.get(lbl.lower(), 0)),
                       S(f"SHV{i}", fontName="Helvetica-Bold", fontSize=14, textColor=SEV_COLORS[i], alignment=TA_CENTER, leading=18))
             for i, lbl in enumerate(SEV_LABELS)],
        ]
        sev_t = Table(sev_data, colWidths=[W/4]*4)
        sev_t.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), C_NAVY_LIGHT),
            ("GRID",          (0,0), (-1,-1), 0.3, C_LG),
            ("TOPPADDING",    (0,0), (-1,-1), 6),
            ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ]))
        story.append(sev_t)
        story.append(Spacer(1, 10))

        # Policy violations detail table
        if policy_violations:
            story.append(Paragraph("Policy Violations Detail",
                                   S("PVH", fontName="Helvetica-Bold", fontSize=10,
                                     textColor=C_RED, spaceAfter=5)))
            vlist = (policy_violations if isinstance(policy_violations[0], dict)
                     else [v.model_dump() for v in policy_violations])
            pv_rows = [["ID", "Policy Name", "Authority", "Severity", "Rule"]]
            for v in vlist:
                sv   = v.get("severity", "low")
                sc   = sev_c.get(sv, C_TEXT_LIGHT)
                pv_rows.append([
                    Paragraph(v.get("policy_id", ""), S("PVID", fontName="Courier-Bold",
                               fontSize=7, textColor=sc)),
                    Paragraph(v.get("name", ""),      S("PVN", fontName="Helvetica-Bold", fontSize=8)),
                    Paragraph(v.get("authority", ""), S("PVA", fontSize=7.5, textColor=C_TEXT_MED)),
                    Paragraph(v.get("severity", "").upper(),
                               S("PVS", fontName="Helvetica-Bold", fontSize=8, textColor=sc)),
                    Paragraph(v.get("rule", ""),      S("PVR", fontSize=7.5, leading=10)),
                ])
            pv_t = Table(pv_rows,
                         colWidths=[1.8*cm, 3.8*cm, 2.8*cm, 1.6*cm, W - 10*cm],
                         repeatRows=1)
            pv_t.setStyle(table_style())
            story.append(pv_t)
        else:
            story.append(Paragraph("✓  No policy violations detected. This application meets all checked compliance requirements.",
                                   S("NV", fontSize=9, textColor=C_GREEN)))

        story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 6. PERMISSION ANALYSIS
    # ═════════════════════════════════════════════════════════════════════════
    section_header("🔐  Permission Analysis")

    total_p     = len(result.permissions)
    dangerous_p = sum(1 for p in result.permissions if p.is_dangerous)
    safe_p      = total_p - dangerous_p

    # Summary row
    psum_data = [[
        Paragraph(str(total_p),     S("PT", fontName="Helvetica-Bold", fontSize=16, textColor=C_NAVY,  alignment=TA_CENTER, leading=20)),
        Paragraph(str(dangerous_p), S("PD", fontName="Helvetica-Bold", fontSize=16, textColor=C_RED,   alignment=TA_CENTER, leading=20)),
        Paragraph(str(safe_p),      S("PS", fontName="Helvetica-Bold", fontSize=16, textColor=C_GREEN, alignment=TA_CENTER, leading=20)),
    ], [
        Paragraph("Total Permissions", S("PTL", fontSize=8, textColor=C_TEXT_MED, alignment=TA_CENTER)),
        Paragraph("Dangerous",         S("PDL", fontSize=8, textColor=C_TEXT_MED, alignment=TA_CENTER)),
        Paragraph("Safe",              S("PSL", fontSize=8, textColor=C_TEXT_MED, alignment=TA_CENTER)),
    ]]
    psum_t = Table(psum_data, colWidths=[W/3]*3)
    psum_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_NAVY_LIGHT),
        ("GRID",          (0,0), (-1,-1), 0.3, C_LG),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
    story.append(psum_t)
    story.append(Spacer(1, 8))

    perm_rows = [["Permission", "Risk Level", "Description"]]
    for p in result.permissions:
        perm_rows.append([
            Paragraph(p.name,
                      S("PN", fontName="Courier", fontSize=7.5, textColor=C_RED if p.is_dangerous else C_TEXT_DARK)),
            Paragraph("⚠ DANGEROUS" if p.is_dangerous else "Normal",
                      S("PRL", fontName="Helvetica-Bold", fontSize=8,
                        textColor=C_RED if p.is_dangerous else C_GREEN)),
            Paragraph(p.description or "—", s_small),
        ])

    perm_t = Table(perm_rows, colWidths=[7*cm, 2.8*cm, W - 9.8*cm], repeatRows=1)
    perm_t.setStyle(table_style())
    story.append(perm_t)
    story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 7. RISK FACTORS
    # ═════════════════════════════════════════════════════════════════════════
    if result.risk_factors:
        section_header("⚠  Risk Factors Identified")
        rf_rows = [["#", "Factor", "Severity", "Details"]]
        for i, rf in enumerate(result.risk_factors, 1):
            sc = sev_c.get(rf.severity, C_TEXT_LIGHT)
            rf_rows.append([
                Paragraph(str(i), s_small),
                Paragraph(rf.factor,  S("RFF", fontName="Helvetica-Bold", fontSize=8.5)),
                Paragraph(rf.severity.upper(),
                          S("RFS", fontName="Helvetica-Bold", fontSize=8, textColor=sc)),
                Paragraph(rf.details, s_small),
            ])
        rf_t = Table(rf_rows, colWidths=[0.7*cm, 5*cm, 2*cm, W - 7.7*cm])
        rf_t.setStyle(table_style())
        story.append(rf_t)
        story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 8. SUSPICIOUS APIS
    # ═════════════════════════════════════════════════════════════════════════
    if result.suspicious_apis:
        section_header("🚨  Suspicious API Calls")
        api_rows = [["#", "API / Method Signature"]]
        for i, api in enumerate(result.suspicious_apis, 1):
            api_rows.append([
                Paragraph(str(i), s_small),
                Paragraph(api, S("API", fontName="Courier", fontSize=8, textColor=C_RED)),
            ])
        api_t = Table(api_rows, colWidths=[0.8*cm, W - 0.8*cm])
        api_t.setStyle(table_style())
        story.append(api_t)
        story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 9. SUSPICIOUS URLS / NETWORK ENDPOINTS
    # ═════════════════════════════════════════════════════════════════════════
    if result.suspicious_urls:
        section_header("🌐  Suspicious Network Endpoints")
        url_rows = [["#", "URL / Endpoint"]]
        for i, url in enumerate(result.suspicious_urls, 1):
            url_rows.append([
                Paragraph(str(i), s_small),
                Paragraph(url, S("URL", fontName="Courier", fontSize=8, textColor=C_AMBER)),
            ])
        url_t = Table(url_rows, colWidths=[0.8*cm, W - 0.8*cm])
        url_t.setStyle(table_style())
        story.append(url_t)
        story.append(Spacer(1, 14))

    # ═════════════════════════════════════════════════════════════════════════
    # 10. DISCLAIMER
    # ═════════════════════════════════════════════════════════════════════════
    disc_t = Table([[Paragraph(
        "DISCLAIMER: This report is generated automatically by APK Guardian using static analysis and "
        "machine learning. It is intended for security research purposes only. Results should be "
        "validated by a qualified security professional before making business or legal decisions. "
        "APK Guardian does not warrant the completeness or accuracy of this report.",
        S("Disc", fontSize=7.5, textColor=C_TEXT_MED, leading=11)
    )]], colWidths=[W])
    disc_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_NAVY_LIGHT),
        ("BOX",           (0,0), (-1,-1), 0.5, C_LG),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING",   (0,0), (-1,-1), 10),
        ("RIGHTPADDING",  (0,0), (-1,-1), 10),
    ]))
    story.append(disc_t)

    # ── Build ──────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=on_first_page, onLaterPages=on_later_pages)
    return buf.getvalue()
